name: classitag

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade poetry
          script/bootstrap
      - name: lint
        run: script/lint
      - name: pytest
        run: script/test
